name: publish-editors-draft
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  publish-editors-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publish
        run: tools/publish

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/website
